name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Build (Debug)
        run: |
          set -eo pipefail
          xcodebuild -project Pegai3d.xcodeproj -scheme Pegai3d -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' build | xcpretty
        env:
          NSUnbufferedIO: YES
      - name: Archive (Release)
        run: |
          set -eo pipefail
          xcodebuild -project Pegai3d.xcodeproj -scheme Pegai3d -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' build | xcpretty
